api/urls.py
from django.conf.urls import url
from api import views
from rest_framework.urlpatterns import format_suffix_patterns
from api.views import CreateView
from api.views import DetailsView 


app_name = 'api'
urlpatterns = [
    url(r'^$', CreateView.as_view(), name="create"),
    url(r'^(?P<pk>[0-9]+)/$', DetailsView.as_view(), name="details"),
]
urlpatterns = format_suffix_patterns(urlpatterns)

cows/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('cowsform.urls')),
	url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
]

cowsform/urls.py
from django.conf.urls import url
from . import views

app_name = 'cowsform'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.ListView, name='list'),
    url(r'^list/(?P<npId>\d+)$', views.ListDetailView, name='detail'),

    #url(r'^thanks/$', views.thanks, name='thanks'),
]

cowsform/models.py
from django.db import models
from django.utils import timezone
from django import forms
from simple_history.models import HistoricalRecords


BC_CHOICES = (
    ('CBC', 'CBC'),
    ('DBC', 'DBC'),
    ('GLBC', 'GLBC'),
    ('MABC', 'MABC'),
    ('MWBC', 'MWBC'),
    ('NEBC', 'NEBC'),
    ('SEBC', 'SEBC'),
    ('SWBC', 'SWBC'),
    ('WBC', 'WBC'),
)

MODEL_CHOICES = (
    ('CHRYSLER', 'CHRYSLER'),
    ('DODGE', 'DODGE'),
    ('JEEP', 'JEEP'),
    ('RAM', 'RAM'),
    ('FIAT', 'FIAT'),
)

MAKE_CHOICES = (
    ('200', '200'),
    ('300', '300'),
    ('Town and Country', 'Town and Country'),
    ('Pacifica', 'Pacifica'),
    ('Challenger','Challenger'),
    ('Charger','Charger'),
    ('Dart','Dart'),
    ('Durango','Durango'),
    ('Grand Caravan','Grand Caravan'),
    ('Journey','Journey'),
    ('Cherokee', 'Cherokee'),
    ('Compass', 'Compass'),
    ('Grand Cherokee', 'Grand Cherokee'),
    ('Patriot', 'Patriot'),
    ('Renegade','Renegade'),
    ('Wrangler','Wrangler'),
    ('Wrangler Unlimited','Wrangler Unlimited'),
    ('Durango','Durango'),
    ('1500','1500'),
    ('2500','2500'),
    ('3500','3500'),
    ('CV', 'CV'),
    ('4500/5500', '4500/5500'),
    ('PROMASTER', 'PROMASTER'),
    ('Promaster CITY', 'Promaster CITY'),
    ('500','500'),
    ('500e','500e'),
    ('500L','500L'),
    ('500X','500X'),
    ('Spider 124','Spider 124'),
)

MONTH_CHOICES = (
    ('JANUARY', 'JANUARY'),
    ('FEBRUARY', 'FEBRUARY'),
    ('MARCH', 'MARCH'),
    ('APRIL', 'APRIL'),
    ('MAY', 'MAY'),
    ('JUNE','JUNE'),
    ('JULY','JULY'),
    ('AUGUST','AUGUST'),
    ('SEPTEMBER','SEPTEMBER'),
    ('OCTOBER','OCTOBER'),
    ('NOVEMBER','NOVEMBER'),
    ('DECEMBER','DECEMBER'),
)

class NamePlate(models.Model):
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    subject_name = models.CharField(max_length=200, verbose_name='Subject Name', unique=True)

    month = models.CharField(
        max_length=100, 
        choices=MONTH_CHOICES,
        verbose_name='Month'
    )

    business_center = models.CharField(
        max_length=4, 
        choices=BC_CHOICES, 
        verbose_name='Business Center'
    )

    states = models.TextField(blank=True)
    zip_codes = models.TextField(blank=True)
    dma = models.TextField(blank=True)
    car_year = models.CharField(max_length=4)
    car_model = models.CharField(
        max_length=100,
        choices=MODEL_CHOICES,
    )
    car_make = models.CharField(
        max_length=100, 
        choices=MAKE_CHOICES
    )
    car_trim = models.CharField(max_length=200, blank=True)
    box_size = models.CharField(max_length=200, blank=True, verbose_name='Box Size')
    wheel_base = models.CharField(max_length=200, blank=True, verbose_name='Wheel Base')

    co_customer_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    co_customer_cash = models.CharField(max_length=200, blank=True, verbose_name='Customer Cash')
    co_bc_bonus_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    co_bc_bonus_cash = models.CharField(max_length=200, blank=True, verbose_name='BC Bonus Cash')
    co_auto_show_bonus_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    co_auto_show_bonus_cash = models.CharField(max_length=200, blank=True, verbose_name='Auto Show Bonus Cash')

    fo_apr_and_term_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    fo_apr_and_term = models.CharField(max_length=200, blank=True, verbose_name='APR & Term')
    fo_bc_bonus_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    fo_bc_bonus_cash = models.CharField(max_length=200, blank=True, verbose_name='BC Bonus Cash')
    fo_auto_show_bonus_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    fo_auto_show_bonus_cash = models.CharField(max_length=200, blank=True, verbose_name='Auto Show Bonus Cash')

    ccfo_customer_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Program ID')
    ccfo_customer_cash = models.CharField(max_length=200, blank=True, verbose_name='Customer Cash')
    ccfo_cc_bc_bonus_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Program ID')
    ccfo_cc_bc_bonus_cash = models.CharField(max_length=200, blank=True, verbose_name='Bonus Cash')
    ccfo_apr_and_term_program_id = models.CharField(max_length=200, blank=True, verbose_name='Program ID')
    ccfo_apr_and_term = models.CharField(max_length=200, blank=True, verbose_name='APR & Term')
    ccfo_aat_bc_bonus_cash_program_id = models.CharField(max_length=200, blank=True, verbose_name='Program ID')
    ccfo_aat_bc_bonus_cash = models.CharField(max_length=200, blank=True, verbose_name='Bonus Cash')

    lo_lease_payment_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    lo_lease_payment = models.CharField(max_length=200, blank=True, verbose_name='Lease Payment')
    lo_term_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    lo_term = models.CharField(max_length=200, blank=True, verbose_name='Term')
    lo_due_at_signing_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    lo_due_at_signing = models.CharField(max_length=200, blank=True, verbose_name='Due at Signing')

    tca_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    total_cash_allowance = models.CharField(max_length=200, blank=True, verbose_name='Total Cash Allowance')

    tv_program_id = models.CharField(max_length=200, blank=True, verbose_name='Programe ID')
    total_values = models.CharField(max_length=200, blank=True, verbose_name='Total Values')
    history = HistoricalRecords()
    def __str__(self):
        return self.subject_name

class CarModel(models.Model):
    name = models.CharField(max_length=200)
    value = models.CharField(max_length=200)
    active = models.BooleanField(default=0)
    def __str__(self):
        return self.name

class CarMake(models.Model):
    carModel = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    value = models.CharField(max_length=200)
    active = models.BooleanField(default=0)
    def __str__(self):
        return self.name

cowsform/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.db import IntegrityError
from django.core.mail import send_mail
from django.urls import reverse
from .models import NamePlate, CarModel, CarMake
from .forms import NamePlateForm
from rest_framework import generics
from .serializers import NamePlateSerializer
from .models import NamePlate
import datetime
 
def index(request):

    cMakeList = "{"
    for model in CarModel.objects.all():
        cMake = CarMake.objects.filter(carModel_id=model.id)
        cMakeList += model.name + ": ["
        for make in cMake:
            cMakeList += "\"" + make.name + "\", "
        cMakeList += "],"
    cMakeList += "}"

    cMakeListActive = "{"
    for model in CarModel.objects.all():
        cMake = CarMake.objects.filter(carModel_id=model.id)
        cMakeListActive += model.name + ": ["
        for make in cMake:
            cMakeListActive += "\"" + str(make.active) + "\", "
        cMakeListActive += "],"
    cMakeListActive += "}"

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NamePlateForm(request.POST)

        # check whether it's valid:
        if form.is_valid():
            try:
                NamePlateInst = NamePlate()

                business_center = form.cleaned_data['business_center']
                subject_name = business_center + '-' + form.cleaned_data['month'] + '-' + form.cleaned_data['car_model'] + '-' + form.cleaned_data['car_make']
                subject_name = subject_name.lower()
                subject_name = subject_name.replace(' ', '_')
                subject_name += '-{:%Y-%m-%d-%H:%M}'.format(datetime.datetime.now())

                NamePlateInst.subject_name = subject_name
                NamePlateInst.month = form.cleaned_data['month']
                NamePlateInst.business_center = business_center
                NamePlateInst.states = form.cleaned_data['states']
                NamePlateInst.zip_codes = form.cleaned_data['zip_codes']
                NamePlateInst.dma = form.cleaned_data['dma']
                NamePlateInst.car_year = form.cleaned_data['car_year']
                NamePlateInst.car_model = form.cleaned_data['car_model']
                NamePlateInst.car_make = form.cleaned_data['car_make']
                NamePlateInst.car_trim = form.cleaned_data['car_trim']
                NamePlateInst.box_size = form.cleaned_data['box_size']
                NamePlateInst.wheel_base = form.cleaned_data['wheel_base']
                NamePlateInst.co_customer_cash_program_id = form.cleaned_data['co_customer_cash_program_id']
                NamePlateInst.co_customer_cash = form.cleaned_data['co_customer_cash']
                NamePlateInst.co_bc_bonus_cash_program_id = form.cleaned_data['co_bc_bonus_cash_program_id']
                NamePlateInst.co_bc_bonus_cash = form.cleaned_data['co_bc_bonus_cash']
                NamePlateInst.co_auto_show_bonus_cash_program_id = form.cleaned_data['co_auto_show_bonus_cash_program_id']
                NamePlateInst.co_auto_show_bonus_cash = form.cleaned_data['co_auto_show_bonus_cash']
                NamePlateInst.fo_apr_and_term_program_id = form.cleaned_data['fo_apr_and_term_program_id']
                NamePlateInst.fo_apr_and_term = form.cleaned_data['fo_apr_and_term']
                NamePlateInst.fo_bc_bonus_cash_program_id = form.cleaned_data['fo_bc_bonus_cash_program_id']
                NamePlateInst.fo_bc_bonus_cash = form.cleaned_data['fo_bc_bonus_cash']
                NamePlateInst.fo_auto_show_bonus_cash_program_id = form.cleaned_data['fo_auto_show_bonus_cash_program_id']
                NamePlateInst.fo_auto_show_bonus_cash = form.cleaned_data['fo_auto_show_bonus_cash']
                NamePlateInst.ccfo_customer_cash_program_id = form.cleaned_data['ccfo_customer_cash_program_id']
                NamePlateInst.ccfo_customer_cash = form.cleaned_data['ccfo_customer_cash']
                NamePlateInst.ccfo_cc_bc_bonus_cash_program_id = form.cleaned_data['ccfo_cc_bc_bonus_cash_program_id']
                NamePlateInst.ccfo_cc_bc_bonus_cash = form.cleaned_data['ccfo_cc_bc_bonus_cash']
                NamePlateInst.ccfo_apr_and_term_program_id = form.cleaned_data['ccfo_apr_and_term_program_id']
                NamePlateInst.ccfo_apr_and_term = form.cleaned_data['ccfo_apr_and_term']
                NamePlateInst.ccfo_aat_bc_bonus_cash_program_id = form.cleaned_data['ccfo_aat_bc_bonus_cash_program_id']
                NamePlateInst.ccfo_aat_bc_bonus_cash = form.cleaned_data['ccfo_aat_bc_bonus_cash']
                NamePlateInst.lo_lease_payment_program_id = form.cleaned_data['lo_lease_payment_program_id']
                NamePlateInst.lo_lease_payment = form.cleaned_data['lo_lease_payment']
                NamePlateInst.lo_term_program_id = form.cleaned_data['lo_term_program_id']
                NamePlateInst.lo_term = form.cleaned_data['lo_term']
                NamePlateInst.lo_due_at_signing_program_id = form.cleaned_data['lo_due_at_signing_program_id']
                NamePlateInst.lo_due_at_signing = form.cleaned_data['lo_due_at_signing']
                NamePlateInst.tcv_program_id = form.cleaned_data['tca_program_id']
                NamePlateInst.total_cash_allowance = form.cleaned_data['total_cash_allowance']
                NamePlateInst.tv_program_id = form.cleaned_data['tv_program_id']
                NamePlateInst.total_values = form.cleaned_data['total_values']
                NamePlateInst.save()

                subject = business_center + ' has submitted something'
                message = business_center + ' has submitted something for you to review, subject name ' + subject_name
                '''
                send_mail(
                    subject,
                    message,
                    'bchevez@hugeinc.com',
                    ['bchevez@hugeinc.com', 'tbresnen@hugeinc.com'],
                    fail_silently=False,
                )
                '''
            except IntegrityError as e:
                form = NamePlateForm()
                return render(request, 'cowsform/form.html', {'form': form, 'error': 'Duplicate subject name', 'carModel': CarModel.objects.all(), 'carMake': cMakeList, 'carMakeActive': cMakeListActive})


            # redirect to a new URL:
            return render(request, 'cowsform/thanks.html', {'form': form, 'npi': NamePlateInst})

        else:
            return render(request, 'cowsform/form.html', {'form': form, 'carModel': CarModel.objects.all(), 'carMake': cMakeList, 'carMakeActive': cMakeListActive})


    # if a GET (or any other method) we'll create a blank form
    else:

        form = NamePlateForm()
        return render(request, 'cowsform/form.html', {'form': form, 'carModel': CarModel.objects.all(), 'carMake': cMakeList, 'carMakeActive': cMakeListActive})

def ListView(request):
    npList= NamePlate.objects.order_by('-pub_date')
    return render(request, 'cowsform/list.html', {'npList': npList})

def ListDetailView(request, npId):
    try:
        nameplate = NamePlate.objects.get(pk=npId)
    except NamePlate.DoesNotExist:
        raise Http404("NamePlate Id does not exist")
    return render(request, 'cowsform/detail.html', {'nameplate': nameplate})

cowsform/templates/cowsform/detail.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>BC Incentive Chart</title>

  <style>
	div.middle {
		width:500px;
    	font-family: "Arial";
	}
	div.left {
		width:40%;
    	text-align:left;
    	float:left;
    	padding:5px;
	}
	div.right {
		width:50%;
    	text-align:left;
    	float:left;
    	padding:5px;
	}

	div.long {
		width:700px;
    	font-family: "Arial";
	}

	div.single {
		width:20%;
    	text-align:left;
    	float:left;
    	padding:5px;
	}

	h1, p {
		font-family: "Arial";
	}

	p.error, ul.errorlist li {
		color:red;
		font-weight:bold;
	}

	ul.errorlist li {
		list-style-type: none;
		margin-left: -40px;
		margin-top: -10px;
		margin-bottom: -10px;
		font-size: 10px;
	}
  </style>

</head>

<body>

<h1>{{ nameplate.subject_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="middle">
	<a href="{% url 'cowsform:list'%}">Return to record list</a>
</div>

<div style="clear:both; padding:10px;"></div>

<div class="middle">
	<div class="left">Month:</div>
	<div class="right">
    	{{ nameplate.month }}
	</div>
</div>

<div class="middle">
	<div class="left">Business Center:</div>
	<div class="right">
    	{{ nameplate.business_center }}
	</div>
</div>

{% if nameplate.states and nameplate.states != "[]" %}
<div class="middle">
	<div class="left">States:</div>
	<div class="right">
	    {{ nameplate.states }}
	</div>
</div>
{% endif %}

{% if nameplate.zip_codes and nameplate.zip_codes != "[]" %}
<div class="middle">
	<div class="left">Zip Codes:</div>
	<div class="right">
        {{ nameplate.zip_codes }}
	</div>
</div>
{% endif %}

{% if nameplate.dma and nameplate.dma != "[]" %}
<div class="middle">
	<div class="left">DMA:</div>
	<div class="right">
    	{{ nameplate.dma }}
	</div>
</div>
{% endif %}

{% if nameplate.car_model %}
<div class="middle">
	<div class="left">Model:</div>
	<div class="right">
		{{ nameplate.car_model }}
    </div>
</div>
{% endif %}

{% if nameplate.car_make %}
<div class="middle">
	<div class="left">Make:</div>
	<div class="right">
    	{{ nameplate.car_make }}
    </div>
</div>
{% endif %}

{% if nameplate.box_size %}
<div class="middle">
	<div class="left">Box Size:</div>
	<div class="right">
    	{{ nameplate.box_size }}
    </div>
</div>
{% endif %}

{% if nameplate.wheel_base %}
<div class="middle">
	<div class="left">Wheel Base:</div>
	<div class="right">
    	{{ nameplate.wheel_base }}
    </div>
</div>
{% endif %}

{% if nameplate.car_trim %}
<div class="middle">
	<div class="left">Trim:</div>
	<div class="right">{{ nameplate.car_trim }}</div>
</div>
{% endif %}

{% if nameplate.car_year %}
<div class="middle">
	<div class="left">Model Year:</div>
	<div class="right">{{ nameplate.car_year }}</div>
</div>
{% endif %}

<div style="clear:both; padding:10px;"></div>

{% if nameplate.co_customer_cash_program_id and nameplate.co_customer_cash and nameplate.co_bc_bonus_cash_program_id and nameplate.co_bc_bonus_cash and nameplate.co_auto_show_bonus_cash and nameplate.co_auto_show_bonus_cash_program_id %}
<div>
	<div class="long">
		<div><b>Cash Offer</b></div>
	</div>

	<div class="long">
		<div class="single">Customer Cash:</div>
		<div class="single">{{ nameplate.co_customer_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.co_customer_cash_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">BC Bonus Cash:</div>
		<div class="single">{{ nameplate.co_bc_bonus_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.co_bc_bonus_cash_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">Auto Show Bonus Cash:</div>
		<div class="single">{{ nameplate.co_auto_show_bonus_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.co_auto_show_bonus_cash_program_id }}</div>
	</div>
</div>
{% endif %}

{% if nameplate.fo_apr_and_term_program_id and nameplate.fo_apr_and_term and nameplate.fo_bc_bonus_cash and nameplate.fo_bc_bonus_cash_program_id and nameplate.fo_auto_show_bonus_cash and nameplate.fo_auto_show_bonus_cash_program_id %}
<div>
	<div class="long">
		<div><b>Finance Offer</b></div>
	</div>

	<div class="long">
		<div class="single">APR and Term:</div>
		<div class="single">{{ nameplate.fo_apr_and_term }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.fo_apr_and_term_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">BC Bonus Cash:</div>
		<div class="single">{{ nameplate.fo_bc_bonus_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.fo_bc_bonus_cash_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">Auto Show Bonus Cash:</div>
		<div class="single">{{ nameplate.fo_auto_show_bonus_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.fo_auto_show_bonus_cash_program_id }}</div>
	</div>
</div>
{% endif %}

{% if nameplate.ccfo_customer_cash_program_id and nameplate.ccfo_customer_cash and nameplate.ccfo_cc_bc_bonus_cash_program_id and nameplate.ccfo_cc_bc_bonus_cash and nameplate.ccfo_apr_and_term_program_id and nameplate.ccfo_apr_and_term and nameplate.ccfo_aat_bc_bonus_cash_program_id and nameplate.ccfo_aat_bc_bonus_cash %}
<div>
	<div class="long">
		<div><b>Combo "Cash or Finance" Offer</b></div>
	</div>

	<div class="long">
		<div class="single">Customer Cash:</div>
		<div class="single">{{ nameplate.ccfo_customer_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.ccfo_customer_cash_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">BC Bonus Cash:</div>
		<div class="single">{{ nameplate.ccfo_cc_bc_bonus_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.ccfo_cc_bc_bonus_cash_program_id }}</div>
	</div>

	<div style="clear:both;"></div>

	<div class="long">
		<b>OR</b>
	</div>

	<div style="clear:both;"></div>

	<div class="long">
		<div class="single">APR and Term:</div>
		<div class="single">{{ nameplate.ccfo_apr_and_term }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.ccfo_apr_and_term_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">BC Bonus Cash:</div>
		<div class="single">{{ nameplate.ccfo_aat_bc_bonus_cash }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.ccfo_aat_bc_bonus_cash_program_id }}</div>
	</div>
</div>
{% endif %}

{% if nameplate.lo_lease_payment_program_id and nameplate.lo_lease_payment and nameplate.lo_term and nameplate.lo_term_program_id and nameplate.lo_due_at_signing and nameplate.lo_due_at_signing_program_id %}
	<div class="long">
		<div><b>Lease Offer</b></div>
	</div>

	<div class="long">
		<div class="single">Lease Payment:</div>
		<div class="single">{{ nameplate.lo_lease_payment }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.lo_lease_payment_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">Term:</div>
		<div class="single">{{ nameplate.lo_term }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.lo_term_program_id }}</div>
	</div>

	<div class="long">
		<div class="single">Due at Signing:</div>
		<div class="single">{{ nameplate.lo_due_at_signing }}</div>
		<div class="single">Program ID:</div>
		<div class="single">{{ nameplate.lo_due_at_signing_program_id }}</div>
	</div>
{% endif %}

{% if nameplate.tca_program_id and nameplate.total_cash_allowance %}
<div class="middle">
	<div><b>Total Cash Allowance-Offer must match Offer Details Section</b></div>
</div>

<div class="middle">
	<div class="left">Program ID:</div>
	<div class="right">
    	{{ nameplate.tca_program_id }}
	</div>
</div>
{% endif %}

{% if nameplate.tv_program_id and nameplate.total_values %}
<div class="middle">
	<div class="left">Total Cash Allowance:</div>
	<div class="right">{{ nameplate.total_cash_allowance }}</div>
</div>

<div style="clear:both; padding:25px;"></div>

<div class="middle">
	<div><b>Total Values-Offer must match Offer Details Section</b></div>
</div>

<div class="middle">
	<div class="left">Program ID:</div>
	<div class="right">
    	{{ nameplate.tv_program_id }}
	</div>
</div>


<div class="middle">
	<div class="left">Total Values:</div>
	<div class="right">{{ nameplate.total_values }}</div>
</div>
{% endif %}

</body>
</html>

cowsform/templates/cowsform/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'cowsform:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No forms are available.</p>
{% endif %}

cowsform/templates/cowsform/list.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>BC Incentive Chart</title>

  <style>
	div.middle {
		width:500px;
    	font-family: "Arial";
	}
	div.left {
		width:40%;
    	text-align:left;
    	float:left;
    	padding:5px;
	}
	div.right {
		width:50%;
    	text-align:left;
    	float:left;
    	padding:5px;
	}

	h1, p {
		font-family: "Arial";
	}

	p.error, ul.errorlist li {
		color:red;
		font-weight:bold;
	}

	ul.errorlist li {
		list-style-type: none;
		margin-left: -40px;
		margin-top: -10px;
		margin-bottom: -10px;
		font-size: 10px;
	}
  </style>
  <script src="/static/fca_cows.js"></script>

</head>

<body>

<h1>List of Records</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% for NamePlate in npList.all %}
<div class="middle">
	<li><a href="{% url 'cowsform:detail' NamePlate.id %}">{{ NamePlate.subject_name }}</a></li>
</div>
{% endfor %}

</body>
</html>

cowsform/templates/cowsform/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'cowsform:detail' question.id %}">Vote again?</a>